-- Run this in Supabase SQL Editor after the existing teacher/enrollment scripts.
-- It adds:
-- 1) monthly obligations per enrollment/month
-- 2) audit history for inserts/updates/deletes

create extension if not exists pgcrypto;

create table if not exists public.monthly_obligations (
  id text primary key default gen_random_uuid()::text,
  enrollment_id text not null,
  student_id text not null,
  teacher_id text,
  course_id text,
  course_name text,
  group_name text,
  month_key text not null,
  pricing_type text not null default 'fixed',
  amount_due numeric not null default 0,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.monthly_obligations
add column if not exists enrollment_id text,
add column if not exists student_id text,
add column if not exists teacher_id text,
add column if not exists course_id text,
add column if not exists course_name text,
add column if not exists group_name text,
add column if not exists month_key text,
add column if not exists pricing_type text not null default 'fixed',
add column if not exists amount_due numeric not null default 0,
add column if not exists archived_at timestamptz,
add column if not exists created_at timestamptz not null default now(),
add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'monthly_obligations_pricing_type_check'
  ) then
    alter table public.monthly_obligations
    add constraint monthly_obligations_pricing_type_check
    check (pricing_type in ('fixed', 'hourly'));
  end if;
end $$;

create unique index if not exists monthly_obligations_enrollment_month_unique
on public.monthly_obligations (enrollment_id, month_key);

create index if not exists monthly_obligations_student_month_idx
on public.monthly_obligations (student_id, month_key);

create index if not exists monthly_obligations_teacher_month_idx
on public.monthly_obligations (teacher_id, month_key);

alter table public.payments
add column if not exists monthly_obligation_id text;

create index if not exists payments_monthly_obligation_id_idx
on public.payments (monthly_obligation_id);

alter table public.monthly_obligations enable row level security;

drop policy if exists "admins read all, teachers read own monthly obligations" on public.monthly_obligations;
drop policy if exists "admins can insert monthly obligations" on public.monthly_obligations;
drop policy if exists "admins can update monthly obligations" on public.monthly_obligations;
drop policy if exists "admins can delete monthly obligations" on public.monthly_obligations;

create policy "admins read all, teachers read own monthly obligations"
on public.monthly_obligations for select
to authenticated
using (
  public.is_app_admin()
  or exists (
    select 1
    from public.teachers t
    where lower(t.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and (
        t.id::text = monthly_obligations.teacher_id::text
        or exists (
          select 1
          from public.enrollments e
          where e.id = monthly_obligations.enrollment_id
            and e.teacher_id = t.id::text
        )
      )
  )
);

create policy "admins can insert monthly obligations"
on public.monthly_obligations for insert
to authenticated
with check (public.is_app_admin());

create policy "admins can update monthly obligations"
on public.monthly_obligations for update
to authenticated
using (public.is_app_admin())
with check (public.is_app_admin());

create policy "admins can delete monthly obligations"
on public.monthly_obligations for delete
to authenticated
using (public.is_app_admin());

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  action text not null,
  actor_email text,
  actor_user_id uuid,
  old_row jsonb,
  new_row jsonb,
  changed_fields text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.audit_log
add column if not exists table_name text,
add column if not exists record_id text,
add column if not exists action text,
add column if not exists actor_email text,
add column if not exists actor_user_id uuid,
add column if not exists old_row jsonb,
add column if not exists new_row jsonb,
add column if not exists changed_fields text[] not null default '{}',
add column if not exists created_at timestamptz not null default now();

create index if not exists audit_log_created_at_idx
on public.audit_log (created_at desc);

create index if not exists audit_log_table_name_idx
on public.audit_log (table_name);

alter table public.audit_log enable row level security;

drop policy if exists "admins can read audit log" on public.audit_log;

create policy "admins can read audit log"
on public.audit_log for select
to authenticated
using (public.is_app_admin());

create or replace function public.audit_changed_fields(old_row jsonb, new_row jsonb)
returns text[]
language sql
stable
set search_path = public
as $$
  select coalesce(array_agg(key order by key), '{}')
  from (
    select key
    from (
      select jsonb_object_keys(coalesce(old_row, '{}'::jsonb) || coalesce(new_row, '{}'::jsonb)) as key
    ) keys
    where coalesce(old_row -> key, 'null'::jsonb) is distinct from coalesce(new_row -> key, 'null'::jsonb)
  ) changed;
$$;

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_data jsonb;
  new_data jsonb;
  changed text[];
begin
  if tg_table_name = 'audit_log' then
    return coalesce(new, old);
  end if;

  old_data := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_data := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;

  if tg_op = 'UPDATE' and old_data = new_data then
    return new;
  end if;

  changed := public.audit_changed_fields(old_data, new_data);

  insert into public.audit_log (
    table_name,
    record_id,
    action,
    actor_email,
    actor_user_id,
    old_row,
    new_row,
    changed_fields
  )
  values (
    tg_table_name,
    coalesce(new_data ->> 'id', old_data ->> 'id'),
    tg_op,
    lower(coalesce(auth.jwt() ->> 'email', '')),
    auth.uid(),
    old_data,
    new_data,
    changed
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists audit_students_changes on public.students;
create trigger audit_students_changes
after insert or update or delete on public.students
for each row execute function public.write_audit_log();

drop trigger if exists audit_teachers_changes on public.teachers;
create trigger audit_teachers_changes
after insert or update or delete on public.teachers
for each row execute function public.write_audit_log();

drop trigger if exists audit_courses_changes on public.courses;
create trigger audit_courses_changes
after insert or update or delete on public.courses
for each row execute function public.write_audit_log();

drop trigger if exists audit_enrollments_changes on public.enrollments;
create trigger audit_enrollments_changes
after insert or update or delete on public.enrollments
for each row execute function public.write_audit_log();

drop trigger if exists audit_monthly_obligations_changes on public.monthly_obligations;
create trigger audit_monthly_obligations_changes
after insert or update or delete on public.monthly_obligations
for each row execute function public.write_audit_log();

drop trigger if exists audit_payments_changes on public.payments;
create trigger audit_payments_changes
after insert or update or delete on public.payments
for each row execute function public.write_audit_log();

drop trigger if exists audit_expenses_changes on public.expenses;
create trigger audit_expenses_changes
after insert or update or delete on public.expenses
for each row execute function public.write_audit_log();
